### ISSUE TITLE
6020_packet_tracer

### ISSUE THREAD

**Issue by TimJustin** [jimmarq/cyfunbook#1]
Once I enrolled I was presented with a "Oops! your browser must have third-party cookies disabled". 

The solution is in the error box telling you to click the module title to load in another window. Wasn't sure if this hiccup was even worth mentioning as I doubt many students would run into this same issue. But wanted to be safe and bring it to your attention anyways,other than that everything is going smoothly!

<img width="960" alt="6020capture" src="https://user-images.githubusercontent.com/105504888/176554742-5a6a421a-1f8b-44a6-9b1f-cf7d5754b914.PNG">

**Comment by jimmarq** [comment]
I added a bullet point discussing the possible cookie error and resolution.
